// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: proto/c_c.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Blank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Blank) Reset() {
	*x = Blank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_c_c_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Blank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blank) ProtoMessage() {}

func (x *Blank) ProtoReflect() protoreflect.Message {
	mi := &file_proto_c_c_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blank.ProtoReflect.Descriptor instead.
func (*Blank) Descriptor() ([]byte, []int) {
	return file_proto_c_c_proto_rawDescGZIP(), []int{0}
}

type Categoria struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nome      string `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	Descricao string `protobuf:"bytes,3,opt,name=descricao,proto3" json:"descricao,omitempty"`
}

func (x *Categoria) Reset() {
	*x = Categoria{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_c_c_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Categoria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Categoria) ProtoMessage() {}

func (x *Categoria) ProtoReflect() protoreflect.Message {
	mi := &file_proto_c_c_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Categoria.ProtoReflect.Descriptor instead.
func (*Categoria) Descriptor() ([]byte, []int) {
	return file_proto_c_c_proto_rawDescGZIP(), []int{1}
}

func (x *Categoria) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Categoria) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Categoria) GetDescricao() string {
	if x != nil {
		return x.Descricao
	}
	return ""
}

type CreateCategoriaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nome      string `protobuf:"bytes,1,opt,name=nome,proto3" json:"nome,omitempty"`
	Descricao string `protobuf:"bytes,2,opt,name=descricao,proto3" json:"descricao,omitempty"`
}

func (x *CreateCategoriaRequest) Reset() {
	*x = CreateCategoriaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_c_c_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCategoriaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoriaRequest) ProtoMessage() {}

func (x *CreateCategoriaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_c_c_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoriaRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoriaRequest) Descriptor() ([]byte, []int) {
	return file_proto_c_c_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCategoriaRequest) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *CreateCategoriaRequest) GetDescricao() string {
	if x != nil {
		return x.Descricao
	}
	return ""
}

type CategoriaList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Categorias []*Categoria `protobuf:"bytes,1,rep,name=categorias,proto3" json:"categorias,omitempty"`
}

func (x *CategoriaList) Reset() {
	*x = CategoriaList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_c_c_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoriaList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoriaList) ProtoMessage() {}

func (x *CategoriaList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_c_c_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoriaList.ProtoReflect.Descriptor instead.
func (*CategoriaList) Descriptor() ([]byte, []int) {
	return file_proto_c_c_proto_rawDescGZIP(), []int{3}
}

func (x *CategoriaList) GetCategorias() []*Categoria {
	if x != nil {
		return x.Categorias
	}
	return nil
}

type CategoriaGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CategoriaGetRequest) Reset() {
	*x = CategoriaGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_c_c_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoriaGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoriaGetRequest) ProtoMessage() {}

func (x *CategoriaGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_c_c_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoriaGetRequest.ProtoReflect.Descriptor instead.
func (*CategoriaGetRequest) Descriptor() ([]byte, []int) {
	return file_proto_c_c_proto_rawDescGZIP(), []int{4}
}

func (x *CategoriaGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CategoriaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Categoria *Categoria `protobuf:"bytes,1,opt,name=categoria,proto3" json:"categoria,omitempty"`
}

func (x *CategoriaResponse) Reset() {
	*x = CategoriaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_c_c_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoriaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoriaResponse) ProtoMessage() {}

func (x *CategoriaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_c_c_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoriaResponse.ProtoReflect.Descriptor instead.
func (*CategoriaResponse) Descriptor() ([]byte, []int) {
	return file_proto_c_c_proto_rawDescGZIP(), []int{5}
}

func (x *CategoriaResponse) GetCategoria() *Categoria {
	if x != nil {
		return x.Categoria
	}
	return nil
}

var File_proto_c_c_proto protoreflect.FileDescriptor

var file_proto_c_c_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x5f, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x07, 0x0a, 0x05, 0x62, 0x6c, 0x61, 0x6e, 0x6b, 0x22, 0x4d,
	0x0a, 0x09, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x6f, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x63, 0x61, 0x6f, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x63, 0x61, 0x6f, 0x22, 0x4a, 0x0a,
	0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x63, 0x61, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x63, 0x61, 0x6f, 0x22, 0x3e, 0x0a, 0x0d, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x0a, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x52, 0x0a, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x73, 0x22, 0x25, 0x0a, 0x13, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x40, 0x0a, 0x11, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x09, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x69, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x52, 0x09, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x69, 0x61, 0x32, 0xe0, 0x02, 0x0a, 0x10, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x12, 0x1a, 0x2e, 0x70, 0x62, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x69, 0x61, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x12, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x22,
	0x00, 0x28, 0x01, 0x12, 0x53, 0x0a, 0x22, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x42, 0x69, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x12, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x69, 0x61, 0x22, 0x00, 0x28, 0x01, 0x12, 0x31, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74,
	0x61, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x73, 0x12, 0x09, 0x2e, 0x70, 0x62,
	0x2e, 0x62, 0x6c, 0x61, 0x6e, 0x6b, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x69, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0c, 0x47,
	0x65, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x12, 0x17, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x69, 0x61, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_c_c_proto_rawDescOnce sync.Once
	file_proto_c_c_proto_rawDescData = file_proto_c_c_proto_rawDesc
)

func file_proto_c_c_proto_rawDescGZIP() []byte {
	file_proto_c_c_proto_rawDescOnce.Do(func() {
		file_proto_c_c_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_c_c_proto_rawDescData)
	})
	return file_proto_c_c_proto_rawDescData
}

var file_proto_c_c_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_c_c_proto_goTypes = []interface{}{
	(*Blank)(nil),                  // 0: pb.blank
	(*Categoria)(nil),              // 1: pb.Categoria
	(*CreateCategoriaRequest)(nil), // 2: pb.CreateCategoriaRequest
	(*CategoriaList)(nil),          // 3: pb.CategoriaList
	(*CategoriaGetRequest)(nil),    // 4: pb.CategoriaGetRequest
	(*CategoriaResponse)(nil),      // 5: pb.CategoriaResponse
}
var file_proto_c_c_proto_depIdxs = []int32{
	1, // 0: pb.CategoriaList.categorias:type_name -> pb.Categoria
	1, // 1: pb.CategoriaResponse.categoria:type_name -> pb.Categoria
	2, // 2: pb.CategoriaService.CreateCategoria:input_type -> pb.CreateCategoriaRequest
	2, // 3: pb.CategoriaService.CreateCategoriaStream:input_type -> pb.CreateCategoriaRequest
	2, // 4: pb.CategoriaService.CreateCategoriaStreamBidirectional:input_type -> pb.CreateCategoriaRequest
	0, // 5: pb.CategoriaService.ListaCategorias:input_type -> pb.blank
	4, // 6: pb.CategoriaService.GetCategoria:input_type -> pb.CategoriaGetRequest
	1, // 7: pb.CategoriaService.CreateCategoria:output_type -> pb.Categoria
	3, // 8: pb.CategoriaService.CreateCategoriaStream:output_type -> pb.CategoriaList
	1, // 9: pb.CategoriaService.CreateCategoriaStreamBidirectional:output_type -> pb.Categoria
	3, // 10: pb.CategoriaService.ListaCategorias:output_type -> pb.CategoriaList
	1, // 11: pb.CategoriaService.GetCategoria:output_type -> pb.Categoria
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_c_c_proto_init() }
func file_proto_c_c_proto_init() {
	if File_proto_c_c_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_c_c_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Blank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_c_c_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Categoria); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_c_c_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCategoriaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_c_c_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategoriaList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_c_c_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategoriaGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_c_c_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategoriaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_c_c_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_c_c_proto_goTypes,
		DependencyIndexes: file_proto_c_c_proto_depIdxs,
		MessageInfos:      file_proto_c_c_proto_msgTypes,
	}.Build()
	File_proto_c_c_proto = out.File
	file_proto_c_c_proto_rawDesc = nil
	file_proto_c_c_proto_goTypes = nil
	file_proto_c_c_proto_depIdxs = nil
}
